-- 0028_faqs_i18n.sql
--
-- Translations for the FAQ questions + answers (es/fr/nl). English stays
-- canonical in the question/answer columns; getFaqs(locale) overlays i18n
-- and falls back to English for anything missing. Category labels are
-- localised in the page copy.ts, so only Q + A live here.

alter table public.faqs add column if not exists i18n jsonb not null default '{}'::jsonb;

update public.faqs set i18n = '{"es": {"question": "¿Cómo reservo?", "answer": "Escríbenos por WhatsApp o rellena el formulario de contacto de esta web. Respondemos en pocas horas con la disponibilidad, un presupuesto a medida y una propuesta de ruta según tus fechas y tu grupo."}, "fr": {"question": "Comment réserver ?", "answer": "Envoyez-nous un WhatsApp ou remplissez le formulaire de demande sur ce site. Nous répondons en quelques heures avec les disponibilités, un devis sur mesure et une suggestion d''itinéraire selon vos dates et votre groupe."}, "nl": {"question": "Hoe boek ik?", "answer": "Stuur ons een WhatsApp of vul het aanvraagformulier op deze site in. We reageren binnen enkele uren met de beschikbaarheid, een offerte op maat en een routevoorstel op basis van uw data en gezelschap."}}'::jsonb where id = 'cac50114-ae88-4568-877a-05e1ca41afc0';
update public.faqs set i18n = '{"es": {"question": "¿Qué incluye el precio?", "answer": "Todos los chárteres incluyen un capitán profesional, combustible, equipo de snorkel, una nevera con hielo, audio Bluetooth, toallas y tumbonas. Los yates más grandes incluyen servicio de azafata y chef a bordo."}, "fr": {"question": "Qu''est-ce qui est inclus dans le prix ?", "answer": "Toutes les locations incluent un capitaine professionnel, le carburant, du matériel de snorkeling, une glacière avec glaçons, un système audio Bluetooth, des serviettes et des transats. Les plus grands yachts incluent un service d''hôtesse et un chef à bord."}, "nl": {"question": "Wat is inbegrepen in de prijs?", "answer": "Alle charters zijn inclusief een professionele kapitein, brandstof, snorkeluitrusting, een koelbox met ijs, Bluetooth-audio, handdoeken en ligbedden. Grotere jachten zijn inclusief stewardessservice en chef aan boord."}}'::jsonb where id = '17e46c81-088a-4865-be2d-d1c42857ab1f';
update public.faqs set i18n = '{"es": {"question": "¿Desde dónde salimos?", "answer": "Todos los chárteres salen de Marina Botafoc, en la ciudad de Ibiza, a poca distancia del aeropuerto y de la mayoría de los hoteles. Tu capitán te enviará la ubicación por WhatsApp esa misma mañana."}, "fr": {"question": "D''où partons-nous ?", "answer": "Toutes les locations partent de Marina Botafoc, à Ibiza-ville, à quelques minutes de l''aéroport et de la plupart des complexes hôteliers. Votre capitaine vous enverra la localisation par WhatsApp le matin même."}, "nl": {"question": "Waar vertrekken we?", "answer": "Alle charters vertrekken vanaf Marina Botafoc in Ibiza-stad, op korte afstand van de luchthaven en de meeste resorts. Uw kapitein deelt ''s ochtends een WhatsApp-locatie."}}'::jsonb where id = '1e8b2886-206b-4416-a059-ced8e5cb50d5';
update public.faqs set i18n = '{"es": {"question": "¿Y la comida y las bebidas?", "answer": "La mayoría de los grupos trae sus propias provisiones o las encarga por adelantado en una de nuestras cocinas de confianza (podemos organizar la entrega en el barco). Para chárteres de día completo y viajes más largos, un chef a bordo es una opción."}, "fr": {"question": "Et la nourriture et les boissons ?", "answer": "La plupart des groupes apportent leurs propres provisions ou les commandent à l''avance auprès de l''une de nos cuisines partenaires (nous pouvons organiser la livraison au bateau). Pour les locations à la journée complète et les séjours plus longs, un chef à bord est possible."}, "nl": {"question": "Hoe zit het met eten en drinken?", "answer": "De meeste groepen nemen hun eigen proviand mee of bestellen vooraf bij een van onze vaste keukens (we kunnen levering aan de boot regelen). Voor volledige charters en langere trips is een chef aan boord een optie."}}'::jsonb where id = 'e129c6a8-29fe-4e9d-a233-82b8aac2d66e';
update public.faqs set i18n = '{"es": {"question": "¿Podemos visitar Formentera?", "answer": "Sí. Formentera está a unos veinte minutos al sur de Ibiza y es el destino más habitual para un chárter de día completo. S''Espalmador, Illetes y Es Caló son las paradas típicas."}, "fr": {"question": "Pouvons-nous visiter Formentera ?", "answer": "Oui. Formentera se trouve à une vingtaine de minutes au sud d''Ibiza et c''est la destination la plus courante pour une location à la journée. S''Espalmador, Illetes et Es Caló sont les escales typiques."}, "nl": {"question": "Kunnen we Formentera bezoeken?", "answer": "Ja. Formentera ligt ongeveer twintig minuten ten zuiden van Ibiza en is de populairste bestemming voor een dagcharter. S''Espalmador, Illetes en Es Caló zijn de gebruikelijke stops."}}'::jsonb where id = '4fb5473a-196a-4a74-91eb-d72cb508932f';
update public.faqs set i18n = '{"es": {"question": "¿Hay una fianza?", "answer": "Sí. La fianza varía según el barco (normalmente entre 1.500 € y 10.000 €) y se retiene como garantía por daños accidentales. Es totalmente reembolsable tras el chárter si no hay incidencias."}, "fr": {"question": "Y a-t-il une caution ?", "answer": "Oui. La caution varie selon le bateau (généralement entre 1 500 € et 10 000 €) et sert de garantie contre les dommages accidentels. Elle est entièrement remboursable après la location si aucun incident ne survient."}, "nl": {"question": "Is er een borg?", "answer": "Ja. De borg verschilt per boot (doorgaans € 1.500–€ 10.000) en dient als waarborg tegen onopzettelijke schade. Volledig terugbetaalbaar na de charter als er geen incidenten zijn."}}'::jsonb where id = 'cdd4d021-208c-4bff-b17c-f6d35e97cd4c';
update public.faqs set i18n = '{"es": {"question": "¿Qué pasa si hace mal tiempo?", "answer": "Lo decide el capitán: si las condiciones no son seguras, reprogramamos el chárter para otro día de la temporada u ofrecemos un reembolso. Nunca navegamos en condiciones en las que no sacaríamos a nuestras propias familias."}, "fr": {"question": "Que se passe-t-il en cas de mauvais temps ?", "answer": "C''est le capitaine qui décide : si les conditions ne sont pas sûres, nous reprogrammons la location à un autre jour de la saison ou proposons un remboursement. Nous ne naviguons jamais dans des conditions où nous n''emmènerions pas nos propres familles."}, "nl": {"question": "Wat als het weer slecht is?", "answer": "De kapitein beslist: als de omstandigheden onveilig zijn, verplaatsen we de charter naar een andere dag in het seizoen of bieden we een terugbetaling. We varen nooit in omstandigheden waarin we onze eigen familie niet zouden meenemen."}}'::jsonb where id = 'aee06805-f56c-40e5-8a9c-e13f2ab4c67a';
update public.faqs set i18n = '{"es": {"question": "¿Se admiten niños?", "answer": "Por supuesto. La mayoría de nuestros chárteres son con familias. En todos los barcos hay chalecos salvavidas de tallas infantiles; dinos cómo es tu grupo y te asignaremos un yate adecuado."}, "fr": {"question": "Les enfants sont-ils les bienvenus ?", "answer": "Bien sûr. La plupart de nos locations se font en famille. Des gilets de sauvetage taille enfant sont présents sur chaque bateau ; indiquez-nous la composition de votre groupe et nous vous proposerons un yacht adapté."}, "nl": {"question": "Zijn kinderen welkom?", "answer": "Natuurlijk. De meeste van onze charters zijn met gezinnen. Op elke boot zijn reddingsvesten in kindermaten aanwezig; laat ons weten hoe uw gezelschap is samengesteld en we koppelen u aan een geschikt jacht."}}'::jsonb where id = '220dc4af-ff9d-4037-a5f8-7fc81c69939b';
